// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input_textfield': string;
  'opacity_hover_effect': string;
  'sidebar_shadow': string;
  'popup_container_default': string;
  'popup_container_transparent_bg': string;
  'scroll_button_shadow': string;
  'shadow_no_pos': string;
  'sidebar_animation_contracted': string;
  'sidebar_animation_expanded': string;
  'folder_item_animation_contracted': string;
  'folder_item_animation_expanded': string;
  'window_item_animation_contracted': string;
  'window_item_animation_expanded': string;
  'scroll_up_button_shadow': string;
  'search_bar_result_container': string;
  'scroll_style': string;
}
export const cssExports: CssExports;
export default cssExports;
