const SET_UP_WINDOWS: string = "SET_UP_WINDOWS";
const SET_MARKED_CURRENT_WINDOWS_ID: string = "SET_MARKED_CURRENT_WINDOWS_ID";
const SET_MARKED_CURRENT_TABS_ID: string = "SET_MARKED_CURRENT_TABS_ID";
const CLEAR_ALL_MARKED: string = "CLEAR_ALL_MARKED";
const SET_CURRENT_TABS_SORT_ORDER: string = "SET_CURRENT_TABS_SORT_ORDER";
const DELETE_MARKED_CURRENT_TABS_ID: string = "DELETE_MARKED_CURRENT_TABS_ID";

const CHANGE_WORKSPACES_VIEWMODE: string = "CHANGE_WORKSPACES_VIEWMODE";

export {
    SET_UP_WINDOWS,
    SET_MARKED_CURRENT_WINDOWS_ID,
    SET_MARKED_CURRENT_TABS_ID,
    CLEAR_ALL_MARKED,
    SET_CURRENT_TABS_SORT_ORDER,
    DELETE_MARKED_CURRENT_TABS_ID,
    
    CHANGE_WORKSPACES_VIEWMODE
}