const SET_MARKED_FOLDERS_ID: string = "SET_MARKED_FOLDERS_ID";
const SET_MULTIPLE_MARKED_FOLDERS_ID: string = "SET_MULTIPLE_MARKED_FOLDERS_ID";
const CLEAR_ALL_MARKED_FOLDERS_ID: string = "CLEAR_ALL_MARKED_FOLDERS_ID";
const SET_FOLDERS_SORT_ORDER: string = "SET_FOLDERS_SORT_ORDER"

export {
    SET_MARKED_FOLDERS_ID,
    SET_MULTIPLE_MARKED_FOLDERS_ID,
    CLEAR_ALL_MARKED_FOLDERS_ID,
    SET_FOLDERS_SORT_ORDER
}