const CREATE_FOLDER: string = "CREATE_FOLDER";
const READ_FOLDER: string = "READ_FOLDER";
const UPDATE_FOLDER: string = "UPDATE_FOLDER";
const DELETE_FOLDER: string = "DELETE_FOLDER";
const SET_UP_FOLDERS: string = "SET_UP_FOLDERS";

export {
    CREATE_FOLDER,
    READ_FOLDER,
    UPDATE_FOLDER,
    DELETE_FOLDER,
    SET_UP_FOLDERS
}