const CREATE_FOLDER: string = "CREATE_FOLDER";
const READ_FOLDER: string = "READ_FOLDER";
const UPDATE_FOLDER: string = "UPDATE_FOLDER";
const DELETE_FOLDER: string = "DELETE_FOLDER";
const SET_UP_FOLDERS: string = "SET_UP_FOLDERS";

const READ_ALL_FOLDERS_FROM_BROWSER: string = "READ_ALL_FOLDERS_FROM_BROWSER";
const READ_ALL_FOLDERS: string = "READ_ALL_FOLDERS";

export {
    CREATE_FOLDER,
    READ_FOLDER,
    UPDATE_FOLDER,
    DELETE_FOLDER,
    SET_UP_FOLDERS,

    READ_ALL_FOLDERS_FROM_BROWSER,
    READ_ALL_FOLDERS,
}