const EDIT_FOLDER: string = "EDIT_FOLDER";
const UPDATE_IN_EDIT_FOLDER: string = "UPDATE_IN_EDIT_FOLDER";
const CLEAR_IN_EDIT_FOLDER: string = "CLEAR_IN_EDIT_FOLDER";
const UPDATE_WINDOW_MANAGER: string = "UPDATE_WINDOW_MANAGER";

export {
    EDIT_FOLDER,
    UPDATE_IN_EDIT_FOLDER,
    CLEAR_IN_EDIT_FOLDER,
    UPDATE_WINDOW_MANAGER
}