const SHOW_FOLDER_CHANGE_WARNING: string = "SHOW_FOLDER_CHANGE_WARNING";
const SHOW_SINGLE_FOLDER_REMOVAL_WARNING: string = "SHOW_SINGLE_FOLDER_REMOVAL_WARNING";
const SHOW_MULTIFOLDER_REMOVAL_WARNING: string = "SHOW_MULTIFOLDER_REMOVAL_WARNING";


export {
    SHOW_FOLDER_CHANGE_WARNING,
    SHOW_SINGLE_FOLDER_REMOVAL_WARNING,
    SHOW_MULTIFOLDER_REMOVAL_WARNING
}