const SET_MARKED_WORKSPACES_ID: string = "SET_MARKED_WORKSPACES_ID";
const SET_MULTIPLE_MARKED_WORKSPACES_ID: string = "SET_MULTIPLE_MARKED_WORKSPACES_ID";
const CLEAR_ALL_MARKED_WORKSPACES_ID: string = "CLEAR_ALL_MARKED_WORKSPACES_ID";
const SET_WORKSPACES_SORT_ORDER: string = "SET_WORKSPACES_SORT_ORDER";

const CHANGE_WORKSPACES_VIEWMODE: string = "CHANGE_WORKSPACES_VIEWMODE";

export {
    SET_MARKED_WORKSPACES_ID,
    SET_MULTIPLE_MARKED_WORKSPACES_ID,
    CLEAR_ALL_MARKED_WORKSPACES_ID,
    SET_WORKSPACES_SORT_ORDER,
    
    CHANGE_WORKSPACES_VIEWMODE
}